const planetasMock = [
    {
        id: 1,
        nome: "Xylar",
        descricao: "Um planeta exuberante com florestas bioluminescentes e rios de cristal.",
        imagem: "https://exemplo.com/xylar.jpg",
    },
    {
        id: 2,
        nome: "Zydonia",
        descricao: "Um planeta desértico com ruínas antigas e cidades subterrâneas.",
        imagem: "https://exemplo.com/zydonia.jpg",
    },
    {
        id: 3,
        nome: "Aethel",
        descricao: "Um planeta gasoso com anéis majestosos e tempestades coloridas.",
        imagem: "https://exemplo.com/aethel.jpg",
    },
    {
        id: 4,
        nome: "Belthor",
        descricao: "Um planeta vulcânico com rios de lava e montanhas de obsidiana.",
        imagem: "https://exemplo.com/belthor.jpg",
    },
    {
        id: 5,
        nome: "Cygnar",
        descricao: "Um planeta oceânico com ilhas flutuantes e criaturas marinhas gigantes.",
        imagem: "https://exemplo.com/cygnar.jpg",
    },
    {
        id: 6,
        nome: "Drakos",
        descricao: "Um planeta rochoso com cânions profundos e formações cristalinas.",
        imagem: "https://exemplo.com/drakos.jpg",
    },
    {
        id: 7,
        nome: "Elysia",
        descricao: "Um planeta com clima temperado e vastas planícies verdejantes.",
        imagem: "https://exemplo.com/elysia.jpg",
    },
    {
        id: 8,
        nome: "Fenris",
        descricao: "Um planeta gelado com geleiras imponentes e auroras boreais constantes.",
        imagem: "https://exemplo.com/fenris.jpg",
    },
    {
        id: 9,
        nome: "Gloomar",
        descricao: "Um planeta sombrio com florestas densas e criaturas noturnas.",
        imagem: "https://exemplo.com/gloomar.jpg",
    },
    {
        id: 10,
        nome: "Hydros",
        descricao: "Um planeta com vastos oceanos e cidades subaquáticas.",
        imagem: "https://exemplo.com/hydros.jpg",
    },
    {
        id: 11,
        nome: "Ignis",
        descricao: "Um planeta com atividade vulcânica intensa e rios de lava.",
        imagem: "https://exemplo.com/ignis.jpg",
    },
    {
        id: 12,
        nome: "Jotnar",
        descricao: "Um planeta com montanhas imponentes e clima glacial.",
        imagem: "https://exemplo.com/jotnar.jpg",
    },
    {
        id: 13,
        nome: "Kryos",
        descricao: "Um planeta com vastas geleiras e criaturas adaptadas ao frio extremo.",
        imagem: "https://exemplo.com/kryos.jpg",
    },
    {
        id: 14,
        nome: "Lumara",
        descricao: "Um planeta com florestas bioluminescentes e rios de cristal.",
        imagem: "https://exemplo.com/lumara.jpg",
    },
    {
        id: 15,
        nome: "Magmar",
        descricao: "Um planeta com vulcões ativos e rios de lava incandescente.",
        imagem: "https://exemplo.com/magmar.jpg",
    },
    {
        id: 16,
        nome: "Nebulos",
        descricao: "Um planeta gasoso com anéis coloridos e tempestades majestosas.",
        imagem: "https://exemplo.com/nebulos.jpg",
    },
    {
        id: 17,
        nome: "Oceana",
        descricao: "Um planeta com vastos oceanos e ilhas flutuantes.",
        imagem: "https://exemplo.com/oceana.jpg",
    },
    {
        id: 18,
        nome: "Pyros",
        descricao: "Um planeta com atividade vulcânica constante e rios de lava.",
        imagem: "https://exemplo.com/pyros.jpg",
    },
    {
        id: 19,
        nome: "Quasar",
        descricao: "Um planeta com formações cristalinas e cânions profundos.",
        imagem: "https://exemplo.com/quasar.jpg",
    },
    {
        id: 20,
        nome: "Ragnar",
        descricao: "Um planeta com montanhas imponentes e clima temperado.",
        imagem: "https://exemplo.com/ragnar.jpg",
    },
    {
        id: 21,
        nome: "Solara",
        descricao: "Um planeta com clima tropical e florestas exuberantes.",
        imagem: "https://exemplo.com/solara.jpg",
    },
    {
        id: 22,
        nome: "Terra Nova",
        descricao: "Um planeta com vastas planícies e clima temperado.",
        imagem: "https://exemplo.com/terranova.jpg",
    },
    {
        id: 23,
        nome: "Umbriel",
        descricao: "Um planeta com florestas densas e criaturas noturnas.",
        imagem: "https://exemplo.com/umbriel.jpg",
    },
    {
        id: 24,
        nome: "Vespera",
        descricao: "Um planeta com auroras boreais constantes e clima gelado.",
        imagem: "https://exemplo.com/vespera.jpg",
    },
    {
        id: 25,
        nome: "Wyvern",
        descricao: "Um planeta com formações rochosas e cânions profundos.",
        imagem: "https://exemplo.com/wyvern.jpg",
    },
    {
        id: 26,
        nome: "Xantus",
        descricao: "Um planeta com rios de cristal e florestas bioluminescentes.",
        imagem: "https://exemplo.com/xantus.jpg",
    },
    {
        id: 27,
        nome: "Yggdrasil",
        descricao: "Um planeta com montanhas imponentes e clima temperado.",
        imagem: "https://exemplo.com/yggdrasil.jpg",
    },
    {
        id: 28,
        nome: "Zephyra",
        descricao: "Um planeta com vastos oceanos e ilhas flutuantes.",
        imagem: "https://exemplo.com/zephyra.jpg",
    },
    {
        id: 29,
        nome: "Aetheria",
        descricao: "Um planeta gasoso com anéis coloridos e tempestades majestosas.",
        imagem: "https://exemplo.com/aetheria.jpg",
    },
    {
        id: 30,
        nome: "Borealis",
        descricao: "Um planeta com auroras boreais constantes e clima gelado.",
        imagem: "https://exemplo.com/borealis.jpg",
    },
];

export default planetasMock;